
spring:
  graphql:
    # GraphQL Console for quick queries at http://localhost:8080/graphiql
    graphiql:
      enabled: true

  datasource:
    url: jdbc:h2:file:./data/telemetry
    username: telemetry
    password: password

  h2:
    console:
      # DB Console for quick checks at http://localhost:8080/h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  tomcat:
    basedir: ./tomcat
